### PR TITLE
Weaving fix

### LINKED ISSUE #9: Fix lane weaving

### PR DESCRIPTION
**Pull request by erik-rosen**
This fixes the weaving problem by always updating the twist command.

### CODE REVIEW

**Comment by erik-rosen** [comment]
See attached video for updated behavior.
[noweaving.mov.zip](https://github.com/erik-rosen/CarND-Capstone/files/5540368/noweaving.mov.zip)

**Review by byapparov — APPROVED** [review]
LGTM.

File: ros/src/waypoint_follower/src/pure_pursuit_core.cpp [hunk 1]
```diff
@@ -251,23 +251,9 @@ bool PurePursuit::verifyFollowing() const
...
-    //ROS_ERROR_STREAM("Not following");
-    twist.angular.z = current_velocity_.twist.linear.x * curvature;
-  }
-  else
-  {
-    twist.angular.z = prev_angular_velocity;
-  }
-
-  prev_angular_velocity = twist.angular.z;
+  twist.angular.z = current_velocity_.twist.linear.x * curvature;
```
Comment (byapparov) [inline ros/src/waypoint_follower/src/pure_pursuit_core.cpp:256]: following_flag - indicates whether car is following the waypoints and if it does no changes are done in the control. removing it means that car is following the waypoints without weaving
